
version: '3.8'

services:
  caddy:
    image: okuka99/dat_frontend:latest  # Jenkins에서 빌드한 이미지 사용
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dat
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: okuka99/dat_backend:latest
    container_name: spring_boot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dat
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    expose:
      - "8080"

volumes:
  mysql_data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    name: app-network
    driver: bridge


