
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234        # 루트 비밀번호 설정
      MYSQL_DATABASE: dat               # 기본 데이터베이스 이름
      MYSQL_USER: user                  # 사용자 이름 설정
      MYSQL_PASSWORD: 1234              # 사용자 비밀번호 설정
    ports:
      - "3306:3306"                     # 호스트의 3306 포트를 컨테이너의 3306 포트에 매핑
    volumes:
      - mysql_data:/var/lib/mysql       # 데이터 유지용 볼륨 설정
    networks:
      - app-network

  app:
    build: .
    container_name: spring_boot_app
    ports:
      - "8080:8080"                     # 호스트의 8080 포트를 컨테이너의 8080 포트에 매핑
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dat
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      # 추가적인 환경 변수 설정 가능
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:

