
services:
  mysql:
    image: mysql:latest
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # 루트 비밀번호 설정
      MYSQL_DATABASE: dat  # 기본 데이터베이스 이름
      MYSQL_USER: user           # 사용자 이름 설정
      MYSQL_PASSWORD: 1234       # 사용자 비밀번호 설정
    ports:
      - "3306:3306"                       # 호스트의 3306 포트를 컨테이너의 3306 포트에 매핑
    volumes:
      - mysql_data:/var/lib/mysql         # 데이터 유지용 볼륨 설정

volumes:
  mysql_data:

