spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dat?serverTimezone=UTC&characterEncoding=UTF-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      static-locations: file:/app/uploads/
file:
  upload-dir: /app/uploads/
